services:

  # Database service
  mattel-database:
    image: postgres:alpine
    restart: no # TODO: Change these to always when deploying
    environment:
      POSTGRES_DB: fundana
      POSTGRES_PASSWORD: admin
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  # Database user interface
  mattel-pgadmin:
    image: dpage/pgadmin4
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80

  # Backend
  mattel-bun:
    image: oven/bun
    restart: no
    environment:
      POSTGRES_URL: postgres://postgres:admin@mattel-database:5432/fundana
    depends_on:
      - mattel-database
    volumes:                   # 1. Create a virtual volume 
      - type: bind             # and bind it to the real folder
        source: ./      # 2. Bind ./backend
        target: /home/bun/app  # to /back (in the container)
    working_dir: /home/bun/app # 3. Set workdir to /home/bun/app
    command: bun run dev       # 4. Run dev script in /home/bun/app
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./
          target: /home/bun/app
          ignore:
            - node_modules/
            - dist/
            - .git/
            - .DS_Store
